<a href="https://colab.research.google.com/github/EunSeong22/text_analysis/blob/main/%EC%8B%A4%EC%8A%B5_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 단어의 벡터와, 문장의 행렬화 실습 :BOW

### CountVectorizer 실습

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
## CountVectorizer 객체 생성

ko_count = CountVectorizer()
en_count = CountVectorizer()

In [ ]:
### 한글 실습용 텍스트 데이터 생성 및 단어 사전 생성하기

# 실습용 텍스트 데이터 생성

ko_text = ['나는 배가 고프다', '내일 점심 뭐 먹지', '내일 공부 해야겠다.', '점심 먹고 공부 해야지']

# fit()함수 이용 --> 자동으로 토큰화, 단어사전 생성

ko_count.fit(ko_text)

ko_vocab = ko_count.vocabulary_
print(ko_vocab)

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}


In [ ]:
### 한글 단어 사전 -> 정렬

sorted_vocab = sorted(ko_vocab.items())
print(sorted_vocab)

[('고프다', 0), ('공부', 1), ('나는', 2), ('내일', 3), ('먹고', 4), ('먹지', 5), ('배가', 6), ('점심', 7), ('해야겠다', 8), ('해야지', 9)]


In [ ]:
ko_sentence1 = [ko_text[0]]
ko_sentence2 = [ko_text[1]]

print(ko_sentence1)
print(ko_sentence2)


ko_matrix1 = ko_count.transform(ko_sentence1)
ko_matrix2 = ko_count.transform(ko_sentence2)
print(ko_matrix1)
print(ko_matrix2)

['나는 배가 고프다']
['내일 점심 뭐 먹지']
  (0, 0)	1
  (0, 2)	1
  (0, 6)	1
  (0, 3)	1
  (0, 5)	1
  (0, 7)	1


In [ ]:
#영어 텍스트 데이터 생성

en_text = ['You already know what The Present is', 'You already know where to find it', 'And you already know how it can make you happy and successful', 'You knew it best when you were younger', 'You have simply forgotten']

# fit()

en_count.fit(en_text)
en_vocab = en_count.vocabulary_

print(en_vocab)

{'you': 23, 'already': 0, 'know': 12, 'what': 20, 'the': 17, 'present': 14, 'is': 9, 'where': 22, 'to': 18, 'find': 4, 'it': 10, 'and': 1, 'how': 8, 'can': 3, 'make': 13, 'happy': 6, 'successful': 16, 'knew': 11, 'best': 2, 'when': 21, 'were': 19, 'younger': 24, 'have': 7, 'simply': 15, 'forgotten': 5}


In [ ]:
### 영어 단어 사전 -> 정렬

sorted_vocab_en = sorted(en_vocab.items())
print(sorted_vocab_en)

[('already', 0), ('and', 1), ('best', 2), ('can', 3), ('find', 4), ('forgotten', 5), ('happy', 6), ('have', 7), ('how', 8), ('is', 9), ('it', 10), ('knew', 11), ('know', 12), ('make', 13), ('present', 14), ('simply', 15), ('successful', 16), ('the', 17), ('to', 18), ('were', 19), ('what', 20), ('when', 21), ('where', 22), ('you', 23), ('younger', 24)]


In [ ]:
en_sentence = [en_text[0]]

print(en_sentence)

#transform().toarray() 함수 사용 --> 자동으로 문장의 행렬화
en_matrix = en_count.transform(en_sentence).toarray()

print(en_matrix)

['You already know what The Present is']
[[1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0]]


### TF-IDF 실습

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
ko_text = ['나는 배가 고프다', '내일 점심 뭐 먹지', '내일 공부 해야겠다.', '점심 먹고 공부 해야지']

tfidf = TfidfVectorizer()

tfidf.fit(ko_text)

TfidfVectorizer()

In [ ]:
# 단어 사전 확인하기
tfidf_vocab = tfidf.vocabulary_

print(tfidf_vocab)

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}


In [ ]:
sentence = [ko_text[0]]

tfidf_matrix = tfidf.transform(sentence).toarray()

print(tfidf_matrix)

[[0.57735027 0.         0.57735027 0.         0.         0.
  0.57735027 0.         0.         0.        ]]


### One-Hot Encoding 실습

In [ ]:
import tensorflow as tf

In [ ]:
### Tokenizer 객체 생성
tokenizer = tf.keras.preprocessing.text.Tokenizer()

In [ ]:
ko_text = ['나는 배가 고프다', '내일 점심 뭐 먹지', '내일 공부 해야겠다.', '점심 먹고 공부 해야지']

tokenizer.fit_on_texts(ko_text)

word_to_index = tokenizer.word_index

print(word_to_index)

# 단어들의 빈도수 확인 --> word_counts 이용

counts = tokenizer.word_counts
print(counts)

{'내일': 1, '점심': 2, '공부': 3, '나는': 4, '배가': 5, '고프다': 6, '뭐': 7, '먹지': 8, '해야겠다': 9, '먹고': 10, '해야지': 11}
OrderedDict([('나는', 3), ('배가', 3), ('고프다', 3), ('내일', 6), ('점심', 6), ('뭐', 3), ('먹지', 3), ('공부', 6), ('해야겠다', 3), ('먹고', 3), ('해야지', 3)])


In [ ]:
sentence = [ko_text[3]]

encoded = tokenizer.texts_to_sequences(sentence)

print(encoded)

[[2, 10, 3, 11]]


In [ ]:
one_hot = tf.keras.utils.to_categorical(encoded)

print(one_hot)

[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]]


## 텍스트 유사도 측정 - 코사인 유사도

In [ ]:
'''
1. 두 개의 문장을 이용하여 Tfidfvectorizer를 이용하여 행렬로 나타낸다.
2. 코사인 유사도 공식을 사용하여 두 문장 간의 유사도를 측정
'''
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
### 영문 텍스트 생성
en_sentences = ['What should I do to be a great scientist?', 'How can I be a scientist in the future?']


In [ ]:
### fit() --> 단어 사전 생성
tfidf.fit(en_sentences)

#생성된 단어 사전 확인하기

vocab= tfidf.vocabulary_

print(vocab)

{'what': 11, 'should': 8, 'do': 2, 'to': 10, 'be': 0, 'great': 4, 'scientist': 7, 'how': 5, 'can': 1, 'in': 6, 'the': 9, 'future': 3}


In [ ]:
### 실습용 텍스트 데이터 생성 --> 각각 문장 --> 리스트 자료형 데이터 생성

en_data1 = [en_sentences[0]]
en_data2 = [en_sentences[1]]

print(en_data1)

['What should I do to be a great scientist?']


In [ ]:
### transform().toarray() 함수 이용 -> 문장의 행렬화 완성
X = tfidf.transform(en_data1).toarray()
Y = tfidf.transform(en_data2).toarray()

print(X)
print(Y)

[[0.29017021 0.         0.4078241  0.         0.4078241  0.
  0.         0.29017021 0.4078241  0.         0.4078241  0.4078241 ]]
[[0.29017021 0.4078241  0.         0.4078241  0.         0.4078241
  0.4078241  0.29017021 0.         0.4078241  0.         0.        ]]


In [ ]:
### 코사인 유사도 측정

# cosine_similarity(X, Y)
similarity = cosine_similarity(X,Y)

#결과 확인하기
print(similarity)

[[0.1683975]]


In [ ]:
ko_tfidf = TfidfVectorizer()
ko_sentences = ["직원이 무단 퇴사를 했는데 손해 배상 청구할 수 있나요?", "무단 퇴사한 직원에 대한 손해 배상 청구가 가능한가요?"]


ko_tfidf.fit(ko_sentences)

ko_vocab = ko_tfidf.vocabulary_

print(ko_vocab)

{'직원이': 7, '무단': 2, '퇴사를': 10, '했는데': 12, '손해': 4, '배상': 3, '청구할': 9, '있나요': 5, '퇴사한': 11, '직원에': 6, '대한': 1, '청구가': 8, '가능한가요': 0}


In [ ]:
ko_data1 = [ko_sentences[0]]
ko_data2 = [ko_sentences[1]]

print(ko_data1)
print(ko_data2)

['직원이 무단 퇴사를 했는데 손해 배상 청구할 수 있나요?']
['무단 퇴사한 직원에 대한 손해 배상 청구가 가능한가요?']


In [ ]:
### transform().toarray() 함수 이용 -> 문장의 행렬화 완성
X = ko_tfidf.transform(ko_data1).toarray()
Y = ko_tfidf.transform(ko_data2).toarray()

print(X)
print(Y)

[[0.         0.         0.27867523 0.27867523 0.27867523 0.39166832
  0.         0.39166832 0.         0.39166832 0.39166832 0.
  0.39166832]]
[[0.39166832 0.39166832 0.27867523 0.27867523 0.27867523 0.
  0.39166832 0.         0.39166832 0.         0.         0.39166832
  0.        ]]
